@startuml
left to right direction
skinparam dpi 300   ' higher DPI image, keeps text sharp
skinparam defaultFontSize 24
skinparam defaultFontColor #ffffffff
skinparam backgroundColor transparent
skinparam ArrowThickness 4   ' shaft thickness
skinparam ArrowColor #000000 ' default color
skinparam ArrowFontSize 24   ' optional: arrow label font
skinparam ArrowHeadSize 18   ' optional: bigger arrowheads

skinparam component {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam rectangle {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam collections {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam node {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam database {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam cloud {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam hexagon {
  BackgroundColor #0078ffAA
  BorderColor #e6f2ff
}

skinparam note {
  BackgroundColor #ffffffff
  FontColor #000000
  BorderColor #000000
}

' External data sources
collections data_nodes [
Non-interoperable 
POLARIN data nodes
]

' External metadata sources
collections metadata_nodes [
Other interoperable
POLARIN data nodes
]

' POLARIN metadata catalogue
node pmc [
<b>POLARIN</b>
<b>metadata</b>
<b>catalogue</b>]

' POLARIN ERDDAP server
database pes [<b>POLARIN</b> 
            <b>ERDDAP-CMS</b>
            <b>server</b>
]

' POLARIN GeoNetwork central data catalogue
rectangle pgcdc [<b>POLARIN GeoNetwork</b> 
<b>central data catalogue</b>] 

' POLARIN Data Hub
cloud "POLARIN Data Hub" as pdh {
    component "Data Catalog" as data_catalog   
    component "Data Viewer" as data_viewer
    component "Data Processing\n Tools" as data_tools
    component "LLM-based \nPOLARIN prompt" as llm_interface
    component "Data management \ntraining materials" as training_materials
}

' API
hexagon "API" as api

metadata_nodes --> pgcdc #000000
note on link
   standardized 
   metadata
end note

pmc --> pgcdc #000000
note on link
   standardized 
   metadata
end note

data_nodes --> pes #000000

pgcdc --> api #000000
note on link
   standardized 
   metadata
end note

api --> pdh #000000
note on link
   enriched
   metadata
end note

pes -> pdh #000000
note on link
  data
end note

pes --> pgcdc #000000
note on link
  metadata
end note

@enduml