@startuml

' External elements
collections "External sources" as ext

' SIOS elements
frame SIOS {
component "harvester" as mdh
component "mdhtransform" as mdt
component "mdfilter" as mdf
component "mdingest" as mdi
component mdc [
mdcat 
----
Catalogue is available
through machine interfaces
offered through pycsw
....
Discovery metadata
contain links to
actual data,
no moving of data
]
}

mdh -> mdt
mdt --> mdf
mdf --> mdi
mdi --> mdc

ext --> mdh

' CNR elements, not sure I understand all
frame CNR {
component "GeoNetwork" as gn
component "ERDDAP/NcWMS" as erddap
component "card/store" as cs
component "webgis" as wg
component "Dashboard" as db
component "Notebooks" as nb
}

gn --> mdc 

gn --> cs
cs --> nb
erddap --> db
erddap --> wg
erddap --> nb

wg --> db
db --> nb


@enduml
