:doctype: article
:pdf-folio-placement: physical
:sectanchors:
:toc: macro
:toclevels: 4
:sectnums:
:sectnumlevels: 6
:chapter-label:
:xrefstyle: short
:title-page:

= Technical documentation: POLARIN minimum discovery metadata profile

<<<

== Minimum discovery metadata profile
A list of generic elements is provided in <<discoverymetadataprofile>>, together with a high level explanation. In <<discoverymetadatamapping>> a suggested mapping between the metadata elements and commonly used metadata
standards is provided.

NOTE: It is expected that a number of metadata standards has to be supported, including various profiles of ISO-19115, schema.org (preferably ESIP's science on schema.org), GCMD DIF, STAC etc.


[[discoverymetadataprofile]]
.A minimum discovery metadata profile has been defined.
[%header, cols="1,4", header=True]
|===
|Element
|Purpose

|Metadata identifier
|A unique identifier for the dataset.
This is used to avoid duplicate records in aggregator catalogues.
Utilisation of UUID with a namespace prefix is recommended.

|Last update of metadata
|An ISO8601 datetime for the last update of the metadata record.

|Title
|To provide a brief explanatory title for the dataset

|Abstract
|A short summary of the dataset, its purpose and how it was generated.

|Temporal Extent
|The temporal spanning of the dataset.
This can be a multi temporal dataset.

|Geographical Extent
|The geographical location of the dataset.
This can be a point, a bounding box, trajectory or a polygon.

|Keywords
|Keywords describing the dataset.
Ideally this comes from controlled vocabularies and describes the variables of the dataset.

|Personnel
|Identification of all people that have contributed to the dataset.
This requires full name, email, affiliation and a role description in the dataset.
The latter has to come from a controlled vocabulary.

|Publisher
|This is identification of the data centre publishing the data.
It contains a long and short name for the data centre and URL to the landing page.

|Use constraint
|This is a license for the data.
This is a URL to the license text and an identifier.
Utilisation of SPDX is recommended.

|Data Access
|This provides direct access to the dataset for download etc.
It is not a landing page, but a direct link to the data and indication using a controlled vocabulary of the access mechanism (ranging from direct download to OPeNDAP and OGC WMS).

|Project
|A list of projects that has contributed to the creation of the dataset.
Polarin has to be one of the projects.

|===

[.landscape]
<<<
[[discoverymetadatamapping]]
.A suggested mapping between the elements of the minimum discovery metadata profile and some commonly used metadata standards.
[%header, cols="1,2,1,1,1,1", header=True]
|===
| Metadata field +
(<<discoverymetadataprofile>>)
| ISO-19115 +
(https://standards.iso.org/iso/19139/[ISO-19139], https://standards.iso.org/iso/19115[ISO-19115])
| DIF 10.2 +
(https://git.earthdata.nasa.gov/projects/EMFD/repos/dif-schemas/browse/10.x/dif_v10.2.xsd[DIF-10.2])
| Schema.org +
(https://schema.org/Dataset[Schema.org])
| DCAT +
(https://www.w3.org/TR/vocab-dcat-2/[DCAT-2.0])
| ACDD +
(https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3[ACDD])

| Metadata identifier
| gmd:fileIdentifier
| Entry_ID
| identifier
| dct:identifier
| id

| Last update of metadata
| gmd:dateStamp
| Metadata_Dates/Metadata_Last_Revision
| dateModified
| dct:modified
| date_metadata_modified

| Title
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title
| Entry_Title
| name
| dct:title
| title

| Abstract
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract
| Summary/Abstract
| description
| dct:description
| summary

| Temporal Extent
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent/gml:TimePeriod/gml:beginPosition (gml:endPosition)
| Temporal_Coverage/Range_DateTime/Beginning_Date_Time (Ending_Date_Time)
| temporalCoverage
| dct:temporal
| time_coverage_start and time_coverage_end

| Geographical Extent
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicBoundingBox/gmd:westBoundLongitude (gmd:eastBoundLongitude, gmd:southBoundLatitude, gmd:northBoundLatitude)
| Spatial_Coverage/Geometry/Bounding_Rectangle/Westernmost_Longitude (Northernmost_Latitude, Southernmost_Latitude, Easternmost_Longitude)
| spatialCoverage
| dct:spatial
| geospatial_lat_min,geospatial_lat_max, geospatial_lon_min,geospatial_lon_max

| Keywords
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword (and gmd:identificationInfo/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName/gmd:CI_Citation/gmd:title)
| Science_Keywords for GCMD Science Keywords (or Ancillary_Keyword for free text)
| keywords
| dcat:theme (or dcat:keyword for free text)
| keywords, keywords_vocabulary

| Personnel
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty/gmd:individualName (gmd:organisationName, gmd:contactInfo and gmd:role)
| Personnel/Role and Personnel/Contact_Person/First_Name (Last_Name, Email)
| creator, contributor
| dcat:contactPoint, dct:creator
| creator_email, creator_institution, creator_name, creator_type, creator_url, contributor_name, contributor_role

| Publisher
| gmd:distributionInfo/gmd:MD_Distribution/gmd:distributor/gmd:MD_Distributor/gmd:distributorContact
| Organization/Organization_Name/Short_Name (Long_Name) and Organization/Organization_URL
| publisher
| dct:publisher
| publisher_name, publisher_email, publisher_institution, publisher_type, publisher_url

| Use constraint
| gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints (type=otherRestrictions) and gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints
| Use_Constraints
| license
| dct:license
| license

| Data Access
| gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage (and gmd:protocol)
| Related_URL/URL_Content_Type/Type and Related_URL/URL
| Distribution  and Distribution/contentUrl
| dcat:distribution (dcat:downloadURL and dcat:accessService)
| NaN

| Project
| can be providede through keywords using "project" as gmd:MD_KeywordTypeCode
| Project/Short_Name (and Long_Name)
| funding
| prov:wasGeneratedBy
| project

|===
[.portrait]
<<<

== Data documentation standards

POLARIN is recommending usage of CF-NetCDF and Darwin Core Archives (DwC-A) for documentation of datasets.
These are internationally recognized file formats that allow for providing embedded metadata
in the file structure itself. By making datasets self-describing, these formats significantly reduce the
need for human intervention in the data life cycle, from ingestion to reuse.

These file formats also align with ENVRI-FAIR recommendations for FAIR (Findable, Accessible, Interoperable, Reusable) data practices.

CF-NetCDF:: NetCDF is a binary format that is most suitable for storing multi-dimensional array-based numerical
scientific data, and can be made FAIR-compliant when combined with the adoption of the Climate and Forecast (CF)
and Attribute Convention for Data Discovery (ACDD) conventions. The file format is recommended for
meteorological, oceanographic, hydrological and glaciological data, but other types of data might also be suitable
for CF-NetCDF.

Darwin Core Archive:: Darwin Core is a data standard originally developed for biodiversity informatics,
though this has expanded to be useful for various types of data associated with one or a list of organisms.
It is the backbone of the Global Biodiversity Information Facility GIBIFfootnote:[GBIF Darwin Core:https://www.gbif.org/darwin-core]
and the Ocean Biodiversity Information System (OBISfootnote:[https://obis.org/]). It consists of a set of comma separated files (CSV) bundled with a
metafile (meta.xml) and using controlled vocabularies to describe the content. A second file (eml.xml)
describes the content and strucuture of the CSVs and links the column headers to the Darwin Core terms.

=== Data granularity

POLARIN recommends to follow the following general guidelines on dataset granularity:

. as a general guideline, always publish data at the highest possible functional granularity (i.e. not individual measurements, but neither several stations combined in one dataset)
. never combine data with different temporal dimensions (e.g. minute and hourly resolutions) in the same dataset.
. never combine data with different vertical dimensions (e.g. surface observations and vertical profiles) in the same dataset.
. if there is a need to reference datasets to collection work (e.g. research cruises or field work), establish this reference through tags on the data or parent/child relations allowing data consumers to collect data based on content and spatio-temporal position.

These guidelines are based on the granularity perspectives practised by the Svalbard Integrated Arctic Earth Observing System (SIOS), which are explained in more detail link:https://github.com/SIOS-Svalbard/SDMSGranularityPerspectives/[here].

=== Types of metadata and machine interoperability

There exists several types of metadata, which serve different purposes. The most relevant in this context are:

Discovery metadata::: This type of metadata describes who did what, where and when, how to access data and potential constraints on the
data. It shall also link to further information on the data, if relevant. It includes information like titles, keywords, abstracts, geographic locations,
dates, and creators. Its primary role is to make resources discoverable in catalogs, repositories, or search
engines.

NOTE: Examples of discovery metadata: ISO-19115, GCMD DIF and ACDD.

Use metadata::: This type of metadata describes the actual contentof a dataset and how it is encoded. The
purpose is to enable the user to understand the data without any further communication. It describes content of
variables using standardised vocabularies, units of variable, encoding of missing values, map projections etc.
Use metadata is especially important to build and provide services and tools on top of the data, as it ensures
that users and machine interfaces can effectively work with the resource once it is found.

NOTE: Examples of use metadata are the Climate and Forecast (CF) conventions and Darwin Core terms.

The use of standardized metadata enables the use of M2M interfaces, which are vital for automating data discovery, integration, and analysis. This is key to support the harvesting
procedures of POLARIN, enhancing usability and enabling complex, automated workflows across various scientific domains.

=== Supporting data interoperability across scientific domains

The standardized structure of DwC-A and CF-NetCDF promotes interoperability, allowing data to be shared and integrated across scientific domains. POLARIN leverages these strengths to bring together heterogeneous datasets, creating a unified and accessible data ecosystem that supports and aims to advance interdisciplinary research collaboration.

By adopting DwC-A and CF-NetCDF, POLARIN complies with ENVRI-FAIR recommendationsfootnote:[For more details, visit https://envri.eu/envri-fair/], which emphasize the importance of using internationally recognized standards, machine-actionable metadata and interoperability to achieve FAIR data principles.

NOTE: When it is not possible to encode data as CF-NetCDF or DwC-A, data can be published in a non-proprietary file format that is easy to consume for users (without specific software) accompanied by a detailed product manual (in PDF format).